---
config:
    MD013:
        line_length: 10000000
        heading_line_length: 70
        code_block_line_length: 10000000
        code_blocks: false
        tables: false
    MD037: false
    MD042: false
